- id:  unicornA_lab_grid_2013-06-01-21-00-47
  desc: grid collected in lab_boxes4
  code:
  - rosstream2boot.ExpLogFromYaml
  - files:
      "file:bag": "${DATASETS}/01-youbot-ros-logs-good/unicornA_lab_grid_2013-06-01-21-00-47.bag"
    annotations:
      robot: &unicornA_base1
        name: unicorn
        shape: unicornA
        profile: base1
      motion:
        agent: andrea  
      environment: &lab_boxes4
        name: vehicles_lab
        config: boxes4
      events:
        disturbances: []
      notes: | 
        no video

- id:  unicornA_lab_grid_2013-06-01-21-04-51
  desc: another grid collected in lab_boxes4
  code:
  - rosstream2boot.ExpLogFromYaml
  - files:
      "file:bag": "${DATASETS}/01-youbot-ros-logs-good/unicornA_lab_grid_2013-06-01-21-04-51.bag"
    annotations:
      robot: *unicornA_base1
      motion:
        agent: andrea  
      environment: *lab_boxes4
      events:
        disturbances: []
      notes: | 
        no video

- id: unicornA_corner3_grid_fine_2013-06-08-19-18-55
  desc: "Fine sampling of the corner3 environment"
  code:
    - rosstream2boot.ExpLogFromYaml
    - files:
        "file:bag": "${DATASETS}/01-youbot-ros-logs-good/unicornA_corner3_grid_fine_2013-06-08-19-18-55.bag"
      annotations:
        robot: *unicornA_base1
        motion:
          agent: teleop
        environment: *lab_boxes4 # XXX
        events:
          disturbances: []
        notes: | 
          no video stream 
          0.03 velocity


- id: unicornA_corner3_grid_all0_2013-06-08-19-26-30
  desc: "Sampling of the corner3 environment"
  code:
    - rosstream2boot.ExpLogFromYaml
    - files:
        "file:bag": "${DATASETS}/01-youbot-ros-logs-good/unicornA_servo_fs1_2013-06-08-15-59-53.bag"
        "file:outside": "${DATASETS}/01-youbot-ros-logs-good/unicornA_corner3_grid_all0_2013-06-08-19-26-30.casio.mov"
      annotations:
        robot: *unicornA_base1
        motion:
          agent: teleop
        environment: *lab_boxes4 # XXX
        events:
          disturbances: []
        notes: | 
          only one video stream



- id: unicornA_lab_gridth_2013-06-01-21-11-15
  desc: pure rotation on theta
  code:
  - rosstream2boot.ExpLogFromYaml
  - files:
      "file:bag": "${DATASETS}/01-youbot-ros-logs-good/unicornA_lab_gridth_2013-06-01-21-11-15.bag"
    annotations:
      robot: *unicornA_base1
      motion:
        agent: andrea  
      environment: *lab_boxes4
      events:
        disturbances: []
      notes: | 
        no video



- id:  unicornA_tran1_2013-04-12-23-34-08
  desc: manually driven along grid
  code:
    - rosstream2boot.ExpLogFromYaml
    - files:
        "file:bag": "${DATASETS}/01-youbot-ros-logs-good/unicornA_tran1_2013-04-12-23-34-08.bag"
        "file:outside": "${DATASETS}/01-youbot-ros-logs-good/unicornA_tran1_2013-04-12-23-34-08.outside.mp4"
      annotations:
        robot: *unicornA_base1
        motion:
          agent: babbler  
        environment: &lab_corner
          name: vehicles_lab
          config: lab_corner
        events:
          disturbances: []
        notes: | 
          Manually driven in a grid
          Note that at the end  I rotate a bit by mistake
                 23 (0.0, 0.1, 0.0)
           1 (0.1, 0.0, 0.0)
          22 (0.0, -0.1, 0.0)
           2 (-0.1, 0.0, 0.0)
           8 (0.0, 0.0, 0.0)
