

- id: unicornA_teleop_nmap_corner3_run_2013-06-05-22-02-03
  desc: "autonomous run of trajectory with camera in unicornA_teleop_nmap_corner3_2013"
  code:
  - rosstream2boot.ExpLogFromYaml
  - files:
      "file:bag": "${DATASETS}/01-youbot-ros-logs-good/unicornA_teleop_nmap_corner3_run_2013-06-05-22-02-03.bag"
    annotations:
      robot: &unicornA_base1
        name: unicorn
        shape: unicornA
        profile: base1
      motion:
        agent: andrea  
      environment: &lab_boxes4
        name: vehicles_lab
        config: boxes4
      events:
        disturbances: []
      notes: | 
        we have 2 video files: Canon + Flip Mino
        autonomous run of unicornA_teleop_nmap_corner3_2013
        $ roslaunch boot_servo_demo exp30c_tr1_cf_strip_navigation_map1.launch


- id: unicornA_teleop_nmap_corner3_run_2013-06-05-22-35-51
  desc: "not sure why this one diverged after a while"
  code:
  - rosstream2boot.ExpLogFromYaml
  - files:
      "file:bag": "${DATASETS}/01-youbot-ros-logs-good/unicornA_teleop_nmap_corner3_run_2013-06-05-22-35-51.bag"
    annotations:
      robot: *unicornA_base1
      motion:
        agent: andrea  
      environment: *lab_boxes4 # XXX
      events:
        disturbances: []
      notes: | 
        ...

- id: unicornA_teleop_nmap_corner3_run_2013-06-05-22-43-23
  desc: "autonomous run of trajectory with hlhr in unicornA_teleop_nmap_corner3_2013"
  code:
  - rosstream2boot.ExpLogFromYaml
  - files:
      "file:bag": "${DATASETS}/01-youbot-ros-logs-good/unicornA_teleop_nmap_corner3_run_2013-06-05-22-43-23.bag"
      "file:outside": "${DATASETS}/01-youbot-ros-logs-good/unicornA_teleop_nmap_corner3_run_2013-06-05-22-43-23.casio.mov"
      "file:outside2": "${DATASETS}/01-youbot-ros-logs-good/unicornA_teleop_nmap_corner3_run_2013-06-05-22-43-23.mino.mp4"
    annotations:
      robot: *unicornA_base1
      motion:
        agent: andrea  
      environment: *lab_boxes4 # XXX
      events:
        disturbances: []
      notes: | 
        we have 2 video files: Canon + Flip Mino
        autonomous run of unicornA_teleop_nmap_corner3_2013
        roslaunch boot_servo_demo exp30-tw1_hlhr-map3.launch
        A few loops, ok.

- id: unicornA_teleop_nmap_corner3_run_2013-06-05-23-20-14
  desc: not good - diverged at start
  code:
  - rosstream2boot.ExpLogFromYaml
  - files:
      "file:bag": "${DATASETS}/01-youbot-ros-logs-good/unicornA_teleop_nmap_corner3_run_2013-06-05-23-20-14.bag"
      "file:outside": "${DATASETS}/01-youbot-ros-logs-good/unicornA_teleop_nmap_corner3_run_2013-06-05-23-20-14.casio.mov"
      "file:outside2": "${DATASETS}/01-youbot-ros-logs-good/unicornA_teleop_nmap_corner3_run_2013-06-05-23-20-14.mino.mp4"
    annotations:
      robot: *unicornA_base1
      motion:
        agent: andrea  
      environment: *lab_boxes4 # XXX
      events:
        disturbances: []
      notes: | 
        ???

- id: unicornA_teleop_nmap_corner3_run_2013-06-05-23-15-48
  desc: "autonomous run of trajectory with hl in unicornA_teleop_nmap_corner3_2013"
  code:
  - rosstream2boot.ExpLogFromYaml
  - files:
      "file:bag": "${DATASETS}/01-youbot-ros-logs-good/unicornA_teleop_nmap_corner3_run_2013-06-05-23-15-48.bag"
      "file:outside": "${DATASETS}/01-youbot-ros-logs-good/unicornA_teleop_nmap_corner3_run_2013-06-05-23-15-48.casio.mov"
      "file:outside2": "${DATASETS}/01-youbot-ros-logs-good/unicornA_teleop_nmap_corner3_run_2013-06-05-23-15-48.mino.mp4"
    annotations:
      robot: *unicornA_base1
      motion:
        agent: andrea  
      environment: *lab_boxes4 # XXX
      events:
        disturbances: []
      notes: | 
        Diverged after a while

- id: unicornA_teleop_nmap_corner3_run_2013-06-05-23-42-11
  desc: "autonomous run of trajectory with hl in unicornA_teleop_nmap_corner3_2013"
  code:
  - rosstream2boot.ExpLogFromYaml
  - files:
      "file:bag": "${DATASETS}/01-youbot-ros-logs-good/unicornA_teleop_nmap_corner3_run_2013-06-05-23-42-11.bag"
    annotations:
      robot: *unicornA_base1
      motion:
        agent: andrea  
      environment: *lab_boxes4 # XXX
      events:
        disturbances: []
      notes: | 
        we have 2 video files: Canon + Flip Mino
        autonomous run of unicornA_teleop_nmap_corner3_2013
        roslaunch boot_servo_demo exp30-tw1_hl-map3.launch
        Two loops, ok.



- id: unicornA_teleop_nmap_corner3_tw1_fs1_2013-06-08-18-38-46
  desc: "with fs1"
  code:
  - rosstream2boot.ExpLogFromYaml
  - files:
      "file:bag": "${DATASETS}/01-youbot-ros-logs-good/unicornA_teleop_nmap_corner3_tw1_fs1_2013-06-08-18-38-46.bag"
      "file:outside": "${DATASETS}/01-youbot-ros-logs-good/unicornA_teleop_nmap_corner3_tw1_fs1_2013-06-08-18-38-46.casio.mov"
      "file:outside2": "${DATASETS}/01-youbot-ros-logs-good/unicornA_teleop_nmap_corner3_tw1_fs1_2013-06-08-18-38-46.mino.mp4"
    annotations:
      robot: *unicornA_base1
      motion:
        agent: navigation
      environment: *lab_boxes4 # XXX
      events:
        disturbances: []
      notes: | 
        shows the effect of gain (lateral translation not good)

- id: unicornA_teleop_nmap_corner3_tw1_fs1g2_2013-06-08-19-10-00
  desc: "same, double gain"
  code:
  - rosstream2boot.ExpLogFromYaml
  - files:
      "file:bag": "${DATASETS}/01-youbot-ros-logs-good/unicornA_teleop_nmap_corner3_tw1_fs1g2_2013-06-08-19-10-00.bag"
      "file:outside": "${DATASETS}/01-youbot-ros-logs-good/unicornA_teleop_nmap_corner3_tw1_fs1g2_2013-06-08-19-10-00.casio.mov"
      "file:outside2": "${DATASETS}/01-youbot-ros-logs-good/unicornA_teleop_nmap_corner3_tw1_fs1g2_2013-06-08-19-10-00.mino.mp4"
    annotations:
      robot: *unicornA_base1
      motion:
        agent: navigation
      environment: *lab_boxes4 # XXX
      events:
        disturbances: []
      notes: | 
        shows the effect of gain (lateral translation not good)

