
# /ros-logs/unicornA_teleop_nmap_2013-05-31-18-55-06.bag. env1 going diagonal
# /ros-logs/unicornA_teleop_nmap_2013-05-31-18-56-01.bag. env2 going back, but forgot logging on

# /ros-logs/unicornA_teleop_nmap_2013-05-31-19-51-24.bag  env2 good, figure 8 translation only
# /ros-logs/unicornA_teleop_nmap_2013-05-31-19-54-07.bag  env2 good, with rotation

- id:  unicornA_teleop_nmap_2013-05-31-19-51-24
  desc: figure 8 translation only
  code:
  - rosstream2boot.ExpLogFromYaml
  - files:
      "file:bag": "${DATASETS}/01-youbot-ros-logs-good/unicornA_teleop_nmap_2013-05-31-19-51-24.bag"
    annotations:
      robot: &unicornA_tran1
        name: unicorn
        shape: unicornA
        profile: tran1
      motion:
        agent: andrea  
      environment: &lab_boxes4
        name: vehicles_lab
        config: boxes4
      events:
        disturbances: []
      notes: | 
        no video

- id:  unicornA_teleop_nmap_2013-05-31-19-54-07
  desc: figure 8 with rotation
  code:
  - rosstream2boot.ExpLogFromYaml
  - files:
      "file:bag": "${DATASETS}/01-youbot-ros-logs-good/unicornA_teleop_nmap_2013-05-31-19-54-07.bag"
    annotations:
      robot: &unicornA_base1
        name: unicorn
        shape: unicornA
        profile: base1
      motion:
        agent: andrea  
      environment: *lab_boxes4
      events:
        disturbances: []
      notes: | 
        no video

- id: unicornA_teleop_nmap_corner3_2013-06-05-21-19-26
  desc: "rectangular trajectory, in the slightly similar map"
  code:
  - rosstream2boot.ExpLogFromYaml
  - files:
      "file:bag": "${DATASETS}/01-youbot-ros-logs-good/unicornA_teleop_nmap_corner3_2013-06-05-21-19-26.bag"
    annotations:
      robot: *unicornA_base1
      motion:
        agent: andrea  
      environment: *lab_boxes4 # XXX
      events:
        disturbances: []
      notes: | 
        we have 2 video files: Canon + Flip Mino


- id: unicornA_teleop_nmap_2013-06-02-18-25-23
  desc: "new map: almost everywhere continuous"
  code:
  - rosstream2boot.ExpLogFromYaml
  - files:
      "file:bag": "${DATASETS}/01-youbot-ros-logs-good/unicornA_teleop_nmap_2013-06-02-18-25-23.bag"
    annotations:
      robot: *unicornA_base1
      motion:
        agent: andrea  
      environment: *lab_boxes4
      events:
        disturbances: []
      notes: | 
        no video

- id: unicornA_teleop_nmap_corner_2013-06-02-20-32-17
  desc: "convex environment"
  code:
  - rosstream2boot.ExpLogFromYaml
  - files:
      "file:bag": "${DATASETS}/01-youbot-ros-logs-good/unicornA_teleop_nmap_corner_2013-06-02-20-32-17.bag"
    annotations:
      robot: *unicornA_base1
      motion:
        agent: andrea  
      environment: *lab_boxes4 # XXX
      events:
        disturbances: []
      notes: | 
        no video

- id: unicornA_teleop_nmap_corner2_2013-06-04-20-29-33
  desc: "another environment"
  code:
  - rosstream2boot.ExpLogFromYaml
  - files:
      "file:bag": "${DATASETS}/01-youbot-ros-logs-good/unicornA_teleop_nmap_corner2_2013-06-04-20-29-33.bag"
    annotations:
      robot: *unicornA_base1
      motion:
        agent: andrea  
      environment: *lab_boxes4 # XXX
      events:
        disturbances: []
      notes: | 
        no video

# unicornA_teleop_nmap_corner2_2013-06-04-21-06-31.bag


- id: unicornA_teleop_nmap_corner2_2013-06-04-21-05-42
  desc: "rectangular trajectory"
  code:
  - rosstream2boot.ExpLogFromYaml
  - files:
      "file:bag": "${DATASETS}/01-youbot-ros-logs-good/unicornA_teleop_nmap_corner2_2013-06-04-21-05-42.bag"
    annotations:
      robot: *unicornA_base1
      motion:
        agent: andrea  
      environment: *lab_boxes4 # XXX
      events:
        disturbances: []
      notes: | 
        no video