
- id: 'exp20_unicornA_ceil'
  desc: 'Camera looking up, differential drive.'
  code:
  - bootstrapping_olympics.library.robots.EquivRobotCausal.from_yaml
  - nuisance: 
    - bootstrapping_olympics.library.nuisances_causal.PureCommandsNuisance
    - delta: 1.0
      n: 10
    robot:
    - bootstrapping_olympics.library.robots.EquivRobot
    - robot: 
      - rosstream2boot.library.ROSRobot.from_yaml
      - adapter: 
        - rosstream2boot.library.ROSRobotAdapter.from_yaml
        - obs_adapter: 
          - rosstream2boot.library.CameraAdapterGray
          - topic: '/cam_eye_right/image_raw/compressed'
            shape: [240, 320]
          cmd_adapter: twist_1_1
          sync:
            policy: obs-first-topic
      cmd_nuisance: []
      obs_nuisance: []