- id: twist_1_1
  desc: '2D Twist'
  code:
  - rosstream2boot.library.TwistAdapter
  - topic: /cmd_vel
    topic_out: /youbot_safety/in_cmd_vel
    max_lin_vel: 1.0
    max_ang_vel: 1.0

- id: twist_xy_1
  desc: '2D Twist'
  code:
  - rosstream2boot.library.TwistAdapterXY
  - topic: /cmd_vel
    topic_out: /youbot_safety/in_cmd_vel
    max_lin_vel: 1.0

- id: twist_un_1
  desc: 'Unicycle dynamics'
  code:
  - rosstream2boot.library.TwistUnicycle
  - topic: /cmd_vel
    topic_out: /youbot_safety/in_cmd_vel
    max_lin_vel: 1.0
    max_ang_vel: 1.0


- id: youbot_b3_back
  desc: "Base and third joint, starting looking straight back."
  code:
  - b2r2b_youbot.YoubotArm
  - arm: '/arm_1'
    max_vel: [1.5, 0, 1.5, 0, 0] # scaling
    joint_home: [2.95, 1, -2.4, 3.3, 2.85] # back
    joint_min: [1.5, 1, -3, 3.3, 2.85]
    joint_max: [4.52, 1, -1.5, 3.3, 2.85]

- id: youbot_b3_back2
  desc: "Base and third joint, starting slightly down."
  code:
  - b2r2b_youbot.YoubotArm
  - arm: '/arm_1'
    max_vel: [1.5, 0, 1.5, 0, 0] # scaling
    joint_home: [2.95, 1, -1.7, 3.3, 2.85] # back
    joint_min: [1.5, 1, -3, 3.3, 2.85]
    joint_max: [4.52, 1, -1.3, 3.3, 2.85]
