
- id: uzhturtle_un1_cf1
  desc: "unicycle, camera"
  code:
  - bootstrapping_olympics.library.robots.EquivRobot
  - robot: 
    - rosstream2boot.ROSRobot.from_yaml
    - adapter:
      - rosstream2boot.ROSRobotAdapter.from_yaml
      - obs_adapter: 
        - rosstream2boot.library.CameraAdapterGray
        - topic: '/camera/image_raw/compressed'
          shape: [120, 160]
        cmd_adapter: twist_un_1
        use_odom_topic: True
        sync:
          policy: obs-first-topic


- id: uzhturtle_un1_cf1_third
  desc: "unicycle, camera"
  code:
  - bootstrapping_olympics.library.robots.EquivRobot
  - robot: uzhturtle_un1_cf1
    obs_nuisance: [camh1d_third]
    cmd_nuisance: []


